# SEE AN EXAMPLE AT https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/mods.toml

# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[32,)"
# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="zlib License"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues"

[[mods]]
    modId="golems"
    version="11.1.4"
    displayName="Extra Golems"
    credits="TheGlitch76, jriwanek, AtelierAmber, and translators - Thanks!"
    authors="skyjay1 and the MMD Team"
    description='''Adds dozens of golems to the minecraft universe, each with unique textures and abilities!'''
    logoFile="golem_logo.png"
[[dependencies.golems]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.golems]]
    modId="quark"
    mandatory=false
    versionRange="[r2.2-261,)"
    ordering="AFTER"
    side="BOTH"
